// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmgrlphiopslkyxmuced.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtZ3JscGhpb3BzbGt5eG11Y2VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MjMyNTMsImV4cCI6MjA2MzM5OTI1M30.Q-_VO1v2-sBim_YLpbebsdIO33WBD7o3YGA5OYk2pYg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});